name: MAC

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install k6 by homebrew
        run: brew install k6

      - name: Local k6 test
        run: k6 run basic/script.js
        
      - name: Download Ngrok
        run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-arm64.zip
      - name: Extract Ngrok Archive
        run: unzip ./ngrok-stable-darwin-arm64.zip
      - name: move Ngrok Archive
        run: sudo mv ./ngrok /usr/bin/ngrok
      - name: Auth
        run: ngrok authtoken 1sZNnDXri0MBoqBy8MvCqTcXzoc_6qWWcEBeGpPqBxiehCtmS
      - name: Enable TS
        run: ngrok tcp 3389
    
#     steps:
#     - name: Get xrdp service1
#       run: |
#         sudo useradd -m guigui && sudo adduser guigui sudo && echo 'guigui:guigui' | sudo chpasswd
#         sudo useradd -m guagua && sudo adduser guagua sudo && echo 'guagua:guagua88' | sudo chpasswd
#     - name: Get xrdp service1
#       run: sudo apt-get install xrdp
#     - name: Get xrdp service1
#       run: | 
#         sudo apt-get install ssh
#         sudo /etc/init.d/ssh start
#     - name: Get xrdp service2
#       run: sudo systemctl enable --now xrdp
#     - name: Get xrdp service3
#       run: sudo ufw allow from any to any port 3389 proto tcp
    
      
      #          sudo passwd root && echo 'password' && echo 'password'
# sudo useradd -m runneradmin && sudo adduser runneradmin sudo && echo 'runneradmin:Techguy20' | sudo chpasswd
      
#     - name: Install ssr server1
#       run: su && echo 'password'
#     - name: Install ssr server2
#       run: sudo bash <(curl -s -L https://git.io/v2ray.sh) && echo '1' && echo '1' && echo '43518' && echo 'N' && echo 'Y' && echo '43512' && echo 'junhua' && echo '2'
#     - name: server
#       run: systemctl start v2ray | systemctl stop firewalld.service | systemctl restart v2ray
#       run: apt install firewalld | systemctl start firewalld | firewall-cmd --zone=public --add-port=43518/tcp --permanent | firewall-cmd --zone=public --add-port=43512/tcp --permanent
      
  
